name: Update TOTO Results

on:
  schedule:
    - cron: '30 18 * * *'  # 6:30pm SGT daily
  workflow_dispatch:

jobs:
  update-toto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Ensure toto_result.json exists
        run: |
          mkdir -p docs
          if [ ! -f docs/toto_result.json ]; then
            echo "[]" > docs/toto_result.json
          fi

      - name: Run scraper
        run: python scraper.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/toto_result.json
          git diff --cached --quiet || git commit -m "Update TOTO result"
          git push
